### ISSUE TITLE
DSL2-Modules.modules.align

### ISSUE THREAD

**Issue by Thandeka325** [grbot/varcall#47]
@phelelani, I have been trying to rerun the align and generate-gvcf modules. But there is an issue that I have been struggling with at line 111 on the main.nf :  include { print_sample_info; log_tool_version_samtools_bwa; log_tool_version_gatk } from './modules/modules-general.nf' . modules-general.nf is not defined and nextflow gives me this error: ERROR nextflow.cli.Launcher - Can't find a matching module file for include: ./modules/modules-general.nf.
At first, I thought maybe you made a mistake and wrote general.nf instead of generate-gvcf.nf

**Comment by phelelani** [comment]
@Thandeka325 - Apologies. I did not push all of the modules onto the DSL2 branch. I have pushed now. Please check.

**Comment by Thandeka325** [comment]
@phelelani, Thanks

**Comment by Thandeka325** [comment]
@phelelani, could you please push the modules again so that  ./modules/modules-location-aware.nf is also on the DSL2 branch.

**Comment by phelelani** [comment]
@Thandeka325 - I am dropping this module. I was using it to optimise the workflow on the cluster. I will make changes to the main script so that its not required.
